DROP TABLE IF EXISTS posts;

CREATE TABLE records (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    emotion TEXT NOT NULL
);